### ISSUE TITLE
Error:  could not find function "lextale"

### ISSUE THREAD

**Issue by Ghozayel** [Ghozayel/Lextale#1]
@BatoolMM
Although I had tested the package and function yesterday and it passed, now when I tried using the function as

> lextale(sample(c(0, 1), replace = TRUE, 600))

followed by installing the package (explained in the read.me file). it shows me this error msg:

> Error in lextale(sample(c(0, 1), replace = TRUE, 600)) :  in lextale(sample(c(0,  @1), replace = TRUE, 600)) :  could not find function "lextale"

Can you please take a look at R codes for the function. Do I need to use the function source() in any stage because I didn't.

**Comment by BatoolMM** [comment]
Feel free to close this issue once PR #2  is merged!
