### ISSUE TITLE
?Lextale is not working

### ISSUE THREAD

**Issue by Ghozayel** [Ghozayel/Lextale#3]
> No documentation for ‘lextale’ in specified packages and libraries:

> you could try ‘??lextale’

I ran this before and found the documentation, but now it shows the above msg, besides the warning massages below:

> Warning messages:
> 1: In withCallingHandlers(.External2(C_parseRd, tcon, srcfile, "UTF-8",  :
>   C:/Users/gmo66/OneDrive/Desktop/R/GitHub/Lextale/man/Lextale-package.Rd:8: unexpected section header '\description'
> 2: In withCallingHandlers(.External2(C_parseRd, tcon, srcfile, "UTF-8",  :
>   C:/Users/gmo66/OneDrive/Desktop/R/GitHub/Lextale/man/Lextale-package.Rd:11: unexpected section header '\seealso'
> 3: In withCallingHandlers(.External2(C_parseRd, tcon, srcfile, "UTF-8",  :
>   C:/Users/gmo66/OneDrive/Desktop/R/GitHub/Lextale/man/Lextale-package.Rd:19: unexpected section header '\keyword'
> 4: In withCallingHandlers(.External2(C_parseRd, tcon, srcfile, "UTF-8",  :
>   C:/Users/gmo66/OneDrive/Desktop/R/GitHub/Lextale/man/Lextale-package.Rd:20: unexpected END_OF_INPUT '

I cannot edit the file in man and the file in the R codes is already got all the required info. Do I need to insert a Roxygen skeleton in the description file? I only did it in the function r codes.

**Comment by BatoolMM** [comment]
`?Lextale` is working for me!

**Comment by Ghozayel** [comment]
Can you send me a pic, I want to use it in my project presentation
I still get the same error message.
