### ISSUE TITLE
MAN folder missing one .rd file

### ISSUE THREAD

**Issue by Ghozayel** [Ghozayel/Lextale#4]
@BatoolMM @popovs
Although a roxygen skeleton had been inserted into the function codes, I have only one rd. file is in the man directory! Do you have any idea whit might be reason(s) behind that? I'd appreciate if you can help :)

Thank you in advance
Gzyl

**Comment by BatoolMM** [comment]
You should only have one `.rda` file generated from the data. It has nothing to do with the roxygen skeleton!
